### ISSUE TITLE
Test Index Broken

### ISSUE THREAD

**Issue by KendrickIW** [floatinghotpot/cordova-plugin-paypalmpl#1]
The test index.html page is broken. The buttons make calls to buyGold. But there is no buyGold function. So assuming it was suppose to be buyGameCoin i changed the calls but doing made the app crash on android

**Comment by floatinghotpot** [comment]
Sorry, it's a bug in the test index.html. During refactoring, some code is moved in wrong order.

Now it's fixed, and tested it okay on iPad (ios code) and Samsung (android code).

Please try again.
