### ISSUE TITLE
Are advance payments possible?

### ISSUE THREAD

**Issue by KendrickIW** [floatinghotpot/cordova-plugin-paypalmpl#3]
This is more of a question than an issue. Do you think it is possible to extend the plugin to support advancePayments? 

Also do you know if this plugin will pass paypal's review process?

**Comment by floatinghotpot** [comment]
No plan working on that, as basic payment works and simplicity is good for mobile apps. :-)

I guess paypal will not review the plugin or the apps using the plugin, as it use the official SDK and paypal app key.

If my guess is wrong, please let me know.

**Comment by artsmc** [comment]
what about guest payments?
