### ISSUE TITLE
PayPalMPLResultDelegate missing from android plugin

### ISSUE THREAD

**Issue by layinka** [floatinghotpot/cordova-plugin-paypalmpl#4]
I tried installing the plugin using the CLI.
When i tried building , i realised that the PayPalMPLResultDelegate class file was missing.
It seems it doesnt get added to the src folder when the plugin was installed.

**Comment by floatinghotpot** [comment]
fixed in commit 24d1c1fec106315f4585d85ae42c30814fdd7f60
